version: '3'

services:
# APP
  jenkins:
    build: .
    image: my-jenkins-env-image
    container_name: my-jenkins-env-container
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes: 
    - ./jenkins-data:/var/jenkins_home

